version: '3'
services:

  server:
    image: zyad99/simple-server
    build: 
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8080:8080"

  client:
    image: zyad99/simple-client
    build: 
      context: .
      dockerfile: Dockerfile.client
    environment:
      SERVER_HOST: server
      SERVER_PORT: 8080

  rabbitmq:
    image: zyad99/rabbitmq
    build: 
      context: .
      dockerfile: Dockerfile.rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"